using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public sealed class CsvReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(FinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.csv");

        var csvContent = $"""
                          
                                      Type,Period,Generated By,Status,Generated At
                                      {report.Type},{report.Period},{report.GeneratedBy},
                                      {report.Status},{report.GeneratedAt}
                          """;

        await File.WriteAllTextAsync(filePath, csvContent, cancellationToken);

        return filePath;
    }
}
