using System.Text;
using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Builders.Reports;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public class CsvReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(CompositeFinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.csv");

        var csvContent = new StringBuilder();
        csvContent.AppendLine("Field,Value");
        csvContent.AppendLine($"Id,{report.Id}");
        csvContent.AppendLine($"Start Date,{report.Period.StartDate:yyyy-MM-dd}");
        csvContent.AppendLine($"End Date,{report.Period.EndDate:yyyy-MM-dd}");
        csvContent.AppendLine($"Report Type,{report.Type}");
        csvContent.AppendLine($"Generated By,{report.GeneratedBy}");
        csvContent.AppendLine($"Status,{report.Status}");
        csvContent.AppendLine($"Generated At,{report.GeneratedAt:yyyy-MM-dd HH:mm:ss}");

        await File.WriteAllTextAsync(filePath, csvContent.ToString(), cancellationToken);

        return filePath;
    }
}