using OfficeOpenXml;
using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public sealed class ExcelReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(FinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.xlsx");

        using var package = new ExcelPackage(new FileInfo(filePath));
        var worksheet = package.Workbook.Worksheets.Add("Report");
       
        worksheet.Cells[1, 1].Value = "Type";
        worksheet.Cells[1, 2].Value = report.Type;
        worksheet.Cells[2, 1].Value = "Period";
        worksheet.Cells[2, 2].Value = report.Period;
        worksheet.Cells[3, 1].Value = "Generated By";
        worksheet.Cells[3, 2].Value = report.GeneratedBy;
        worksheet.Cells[4, 1].Value = "Status";
        worksheet.Cells[4, 2].Value = report.Status;
        worksheet.Cells[5, 1].Value = "Generated At";
        worksheet.Cells[5, 2].Value = report.GeneratedAt;

        await package.SaveAsync(cancellationToken);

        return filePath;
    }
}
