using OfficeOpenXml;
using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public class ExcelReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(CompositeFinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.xlsx");

        using var package = new ExcelPackage(new FileInfo(filePath));
        var worksheet = package.Workbook.Worksheets.Add("Report");
        worksheet.Cells[1, 1].Value = "Field";
        worksheet.Cells[1, 2].Value = "Value";
        worksheet.Cells[2, 1].Value = "Id";
        worksheet.Cells[2, 2].Value = report.Id.ToString();
        worksheet.Cells[3, 1].Value = "Start Date";
        worksheet.Cells[3, 2].Value = report.Period.StartDate.ToString("yyyy-MM-dd");
        worksheet.Cells[4, 1].Value = "End Date";
        worksheet.Cells[4, 2].Value = report.Period.EndDate.ToString("yyyy-MM-dd");
        worksheet.Cells[5, 1].Value = "Report Type";
        worksheet.Cells[5, 2].Value = report.Type.ToString();
        worksheet.Cells[6, 1].Value = "Generated By";
        worksheet.Cells[6, 2].Value = report.GeneratedBy.ToString();
        worksheet.Cells[7, 1].Value = "Status";
        worksheet.Cells[7, 2].Value = report.Status.ToString();
        worksheet.Cells[8, 1].Value = "Generated At";
        worksheet.Cells[8, 2].Value = report.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss");

        await package.SaveAsync(cancellationToken);

        return filePath;
    }
}