using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public sealed class HtmlReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(FinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.html");

        var htmlContent = $"""
                           
                                       <html>
                                       <head>
                                           <title>Financial Report - {report.Type}</title>
                                       </head>
                                       <body>
                                           <h1>Financial Report - {report.Type}</h1>
                                           <p>Period: {report.Period}</p>
                                           <p>Generated By: {report.GeneratedBy}</p>
                                           <p>Status: {report.Status}</p>
                                           <p>Generated At: {report.GeneratedAt}</p>
                                       </body>
                                       </html>
                           """;

        await File.WriteAllTextAsync(filePath, htmlContent, cancellationToken);

        return filePath;
    }
}
