using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public class HtmlReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(CompositeFinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.html");

        var htmlContent = $"""
                           
                                           <html>
                                           <head>
                                               <title>Financial Report - {report.Id}</title>
                                           </head>
                                           <body>
                                               <h1>Financial Report - {report.Id}</h1>
                                               <p>Start Date: {report.Period.StartDate:yyyy-MM-dd}</p>
                                               <p>End Date: {report.Period.EndDate:yyyy-MM-dd}</p>
                                               <p>Report Type: {report.Type}</p>
                                               <p>Generated By: {report.GeneratedBy}</p>
                                               <p>Status: {report.Status}</p>
                                               <p>Generated At: {report.GeneratedAt:yyyy-MM-dd HH:mm:ss}</p>
                                           </body>
                                           </html>
                           """;

        await File.WriteAllTextAsync(filePath, htmlContent, cancellationToken);

        return filePath;
    }
}