using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public class TxtReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(CompositeFinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.txt");

        var txtContent = $"""
                          
                                          Financial Report - {report.Id}
                                          Start Date: {report.Period.StartDate:yyyy-MM-dd}
                                          End Date: {report.Period.EndDate:yyyy-MM-dd}
                                          Report Type: {report.Type}
                                          Generated By: {report.GeneratedBy}
                                          Status: {report.Status}
                                          Generated At: {report.GeneratedAt:yyyy-MM-dd HH:mm:ss}
                          """;

        await File.WriteAllTextAsync(filePath, txtContent, cancellationToken);

        return filePath;
    }
}