using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.Reports.Generators;

public sealed class TxtReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(FinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.txt");

        await File.WriteAllTextAsync(filePath, 
            $"Financial Report - {report.Type}\n" +
            $"Period: {report.Period}\n" +
            $"Generated By: {report.GeneratedBy}\n" +
            $"Status: {report.Status}\n" +
            $"Generated At: {report.GeneratedAt}", cancellationToken);

        return filePath;
    }
}
