using PayVerse.Application.Reports.Services;
using PayVerse.Domain.Entities.Reports;

namespace PayVerse.Infrastructure.ReportGenerators;

internal sealed class PdfReportGenerator : IReportGenerator
{
    public async Task<string> GenerateAsync(FinancialReport report, CancellationToken cancellationToken)
    {
        var filePath = Path.Combine("GeneratedReports", $"{report.Id}.pdf");

        await using var stream = new FileStream(filePath, FileMode.Create);
        await using var writer = new StreamWriter(stream);
        
        await writer.WriteLineAsync($"Financial Report - {report.Type}");
        await writer.WriteLineAsync($"Period: {report.Period}");
        await writer.WriteLineAsync($"Generated By: {report.GeneratedBy}");
        await writer.WriteLineAsync($"Status: {report.Status}");
        await writer.WriteLineAsync($"Generated At: {report.GeneratedAt}");

        return filePath;
    }
}
